name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      uses: php-actions/composer@v5
      with:
        php_extensions: sockets
    
    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - run: npm ci
    
    - name: Run tests
      run: vendor/bin/phpunit tests
    
    
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: php-actions/composer@v5
        with:
          php_extensions: sockets

      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@v3
        with:
          php_extensions: sockets
          path: src/
