name: CI

on: [push]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: php-actions/composer@v5
        with:
          php_extensions: sockets

      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@v3
        with:
          php_extensions: sockets
          path: src/
